version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: edupassword
      POSTGRES_DB: edudb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  app:
    build: .
    command: node server.js
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=eduuser
      - DB_PASSWORD=edupassword
      - DB_NAME=edudb
      - NODE_ENV=production
    depends_on:
      - db

volumes:
  db_data:
